### ISSUE TITLE
Problem with downloading zipped data

### ISSUE THREAD

**Issue by tinahe75** [KDDI-AI-Center/LFW-emotion-dataset#1]
Hello, I was wondering if the data is downloadable? I tried downloading the zip folders, but they seem to be invalid. Thanks!

**Comment by amrta-coder** [comment]
Hi! Would you please try to directly clone the repo, which has some data not included in the zip folders?

**Comment by tinahe75** [comment]
Thank you for the update! 
When I try to clone the repo, I still get this error message:
"This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access."

**Comment by amrta-coder** [comment]
Thanks for letting me know!
We will solve this problem today, maybe by using some other data-sharing websites.
If you have any idea or suggestion, please let me know it.

**Comment by amrta-coder** [comment]
By the way, we have received an e-mail, in which the same problem is mentioned. We are wondering if the e-mail is from you? If that e-mail is from you, please reply to the e-mail and let us know it. We will send you the download link directly by e-mail.
