### ISSUE TITLE
data error

### ISSUE THREAD

**Issue by yy2yy** [KDDI-AI-Center/LFW-emotion-dataset#2]
Hello，your work is great. I'm interested in your data，the download zip(LFW-FER.zip，M-LFW-FER.zip, M-LFW-FER-face-cut.zip) in the data folder has errors. Can you upload the correct data, please？ Thank you very much.

**Comment by amrta-coder** [comment]
@yy2yy 
would you please send us an e-mail to bo-yang@kddi-research.jp, and we will provide you with the download link?
